apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-backend
  template:
    metadata:
      labels:
        app: nest-backend
    spec:
      containers:
        - name: nest-backend
          image: gcr.io/<YOUR_PROJECT_ID>/nest-backend:latest
          env:
            - name: DB_HOST
              value: "10.241.0.3"
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: "admin"
            - name: DB_PASSWORD
              value: "StrongPassword123"
            - name: DB_NAME
              value: "app_db"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nest-backend
spec:
  selector:
    app: nest-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP